/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: maxdragonn (https://sketchfab.com/maxdragon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/office-lamp-d934c6b791c34e0fafc30e9625b4c55c
title: office lamp
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lamp.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.lamp_a_0.geometry} material={materials.lamp_a} />
      </group>
    </group>
  )
}

useGLTF.preload('/lamp.gltf')
